GET http://localhost:8080/api/vehicle
Content-Type: */*

###

POST http://localhost:8080/api/vehicle
Content-Type: application/json

{
  "brand": "nissan",
  "model": "micra"
}

###
GET http://localhost:8080/q/health
Content-Type: */*
